sudo: required
language: bash

# exclude tags
branches:
  except:
    - /^\d+.\d+.\d+$/

services:
  - docker

cache:
  directories:
  # these directories are typically caches for our common build tools
  # travis will keep persistent cache across builds to reduce
  # the amount of redundant work these build tools to do
  - "$HOME/node_modules"

env:
  global:
    - CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

script:
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then docker run -t -e CI_BUILD_NUMBER=$CI_BUILD_NUMBER -e NPM_TOKEN=$NPM_TOKEN -v $PWD:/usr/src/app -w /usr/src/app node:6  make publish; else  docker run -t -e CI_BUILD_NUMBER=$CI_BUILD_NUMBER -e NPM_TOKEN=$NPM_TOKEN -v $PWD:/usr/src/app -w /usr/src/app node:6  make test; fi'

after_success:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$(make version)
  - echo "GIT_TAG=$GIT_TAG"
  - >
    [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] &&
    git tag $GIT_TAG -f -a -m "Version $GIT_TAG built by Travis CI - https://travis-ci.com/$TRAVIS_REPO_SLUG/builds/$TRAVIS_JOB_ID"
    || true
  - >
    [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] &&
    git push -q https://$GITHUB_USER:$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG --tags || true
